# Generated by Django 2.2.6 on 2019-11-14 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=100)),
                ('total', models.FloatField(default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio_diario', models.FloatField(default=0.0)),
                ('max_pax', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='reservas/images/')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.Ciudad')),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Propiedades',
            },
        ),
        migrations.CreateModel(
            name='Fecha_Alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alq', models.DateField()),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.Propiedad')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.Reserva')),
            ],
            options={
                'verbose_name_plural': 'Fechas Alquileres',
            },
        ),
    ]
