# Generated by Django 2.2.6 on 2019-11-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_auto_20191114_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(default='reservas/static/reservas/images/bg.jpg', upload_to='images'),
        ),
    ]
